#!/bin/sh
#***********************************************************************
# Copyright © 2016 Broadcom.  The term "Broadcom" refers
# to Broadcom Limited and/or its subsidiaries.
#
#**********************************************************************
#
# @filename relativepath
#
# @purpose Target specific make file to build Openapps features
#
# @component base
#
# @comments
#
# @create 11/15/2014
#
# @author sagrawal
# @end
#
#*********************************************************************

if [ $# -lt 2 ]; then
        echo "Usage: $(basename $0) <base path> <target path>"
        exit 1
fi

relative=$(perl -MFile::Spec -e 'print File::Spec->abs2rel("'$2'","'$1'")')

echo $relative
